

// src/constants/routes.ts
export const ROUTES = {
  user: {
    signup: "/user/signup",
    login: "/user/login",
    verifyOtp: "/user/verifyOtp",
    resentOtp: "/user/resentOtp",
    me: "/user/me",
    doctorDetails: "/user/doctorDetails",
    forgotPassword: "/user/forgotPassword",
    recoveryPassword: "/user/recoveryPassword",
    verifyRecoveryPassword: "/user/verifyRecoveryPassword",
    resetPassword: (email: string) => `/user/resetPassword/${email}`,
    changePassword: (userId: string) => `/user/changePassword/${userId}`,
    refreshToken: "/user/refreshToken",
    updateProfile: (userId: string) => `/user/updateProfile/${userId}`,
    updateDp: (userId: string) => `/user/updateDp/${userId}`,
    logout: "/user/logout",
    doctors: "/user/doctors",
    conversation: (userId: string) => `/user/conversation/${userId}`,
    message: (conversationId: string) => `/user/message/${conversationId}`,
    sessions: "/user/sessions",
    bookedSlots: "/user/bookedSlots",
    stripe: {
      createOneTimePayment: "/user/stripe/create-one-time-payment",
    },
    getAppointments: "/user/getAppointments",
    cancelAppointment: "/user/cancelAppointment",
    directFileUpload: "/user/directFileUpload",
    getAnalysisReport : "/user/getAnalysisReports",
    cancelAnalysisReport : "/user/cancelAnalysisReports",
    walletPayment : "/user/walletPayment",
    notifications : "/user/notifications",
    getBlogs: "/user/getBlogs",
    dashboard: "/user/dashboard",
    prescription: "/user/prescription",
    unAvailableDays: "/user/unAvailableDays",
    unAvailableSessions: "/user/unAvailableSessions",
    latestPrescription : "/user/latestPrescription",
    latestDoctorPrescription : "/user/latestDoctorPrescription",
    activeBooking:"/user/activeBooking",    
    getTransactions: "/user/getTransactions",
    
  },


  doctor: {
    signup: "/doctor/signup",
    me: "/doctor/me",
    login: "/doctor/login",
    verifyOtp: "/doctor/verifyOtp",
    resentOtp: "/doctor/resentOtp",
    refreshToken: "/doctor/refreshToken",
    logout: "/doctor/logout",
    stripe: {
      createCheckoutSession: "/doctor/stripe/create-checkout-session",
    },
    verifySubscription: "/doctor/verifySubscription",
    changePassword: (userId: string) => `/doctor/changePassword/${userId}`,
    updateProfile: (userId: string) => `/doctor/updateProfile/${userId}`,
    updateDp: (userId: string) => `/doctor/updateDp/${userId}`,
    conversation: (doctorId: string) => `/doctor/conversation/${doctorId}`,
    getMessage: (conversationId: string) => `/doctor/message/${conversationId}`,
    message: "/doctor/message",
    sessions: "/doctor/sessions",
    session: "/doctor/session",
    getAppointments: "/doctor/getAppointments",
    getAnalysisReport: "/doctor/getAnalysisReports",
    submitAnalysisReport: "/doctor/submitAnalysisReports",
    directFileUpload: "/doctor/directFileUpload",
    cancelAnalysisReports: "/doctor/cancelAnalysisReports",
    getSubscriptions: "/doctor/getSubscriptions",
    getBlogs: "/doctor/getBlogs",
    blog: "/doctor/blog",
    advertisement: "/doctor/advertisement",
    getAdvertisements: "/doctor/advertisements",
    notifications : "/doctor/notifications",
    prescription : "/doctor/prescription",
    prescriptions : "/doctor/prescriptions",
    getUser: "/doctor/getUser",
    dashboard: "/doctor/dashboard",
    requestPayout : "/doctor/requestPayout",
    bookedSlots: "/doctor/bookedSlots",
    getPayouts:"/doctor/getPayouts",
    cancelAppointment: "/doctor/cancelAppointment",
    unAvailableDays: "/doctor/unAvailableDays",
    unAvailableSessions: "/doctor/unAvailableSessions",
    appointmentStats: "/doctor/appointmentStats",
    reportsStats:"/doctor/ReportsStats",
    payoutsStats:"/doctor/payoutsStats",
    getRevenues:"/doctor/getRevenues",

  },


  admin: {
    login: "/admin/login",
    forgotPassword: "/admin/forgotPassword",
    recoveryPassword: "/admin/recoveryPassword",
    resetPassword: (email: string) => `/admin/resetPassword/${email}`,
    refreshToken: "/admin/refreshToken",
    logout: "/admin/logout",
    users: "/admin/users",
    doctors: "/admin/doctors",
    doctor: (id: string) => `/admin/doctor/${id}`,
    verifyDoctor: (id: string) => `/admin/doctor/${id}/verify`,
    declineDoctor: (id: string) => `/admin/doctor/${id}/decline`,
    manageUsers: {
      block: (id: string) => `/admin/users/${id}/block`,
      unblock: (id: string) => `/admin/users/${id}/unblock`,
    },
    manageDoctors: {
      block: (id: string) => `/admin/doctors/${id}/block`,
      unblock: (id: string) => `/admin/doctors/${id}/unblock`,
    },
    getAppointments : "/admin/getAppointments",
    getSubscriptions: "/admin/getSubscriptions",
    createSubscription: "/admin/createSubscription",
    deActivateSubscription: "/admin/deActivateSubscription",
    activateSubscription: "/admin/activateSubscription",
    updateSubscription: "/admin/updateSubscription",
    getUserAnalytics:(filter:string) => `/admin/getUserAnalytics/${filter}`,
    getDoctorAnalytics:(filter:string) => `/admin/getDoctorAnalytics/${filter}`,
    getTotalAnalytics : "/admin/getTotalAnalytics",
    getTransactions : "/admin/getTransactions",
    payouts:"/admin/payouts",
    appointmentStats: "/admin/appointmentStats",
    reportsStats:"/admin/ReportsStats",

    
    
  },
  
};